"""Abstention and Selective Prediction Policy for Veyra (Gate 9 / Phase J).

Defines rigorous abstention criteria to prevent hallucination, overconfident failure predictions,
and unauthorized forecasts under extreme out-of-distribution (OOD) or unverified reference conditions.
"""

from enum import Enum
from typing import Any, Dict, Optional
from pydantic import BaseModel, Field


class AbstentionReason(str, Enum):
    """Reason codes for declining operational prediction."""
    OOD_EXCEEDED = "OOD_EXCEEDED"
    EPISTEMIC_UNCERTAINTY_HIGH = "EPISTEMIC_UNCERTAINTY_HIGH"
    REFERENCE_UNAVAILABLE = "REFERENCE_UNAVAILABLE"
    PHYSICAL_INCONSISTENCY = "PHYSICAL_INCONSISTENCY"
    SEVERITY_LIMIT_UNSUPPORTED = "SEVERITY_LIMIT_UNSUPPORTED"


class OperationalPredictionStatus(str, Enum):
    """Operational prediction status."""
    PREDICT = "PREDICT"
    ABSTAIN = "ABSTAIN"
    DIAGNOSTIC_ONLY = "DIAGNOSTIC_ONLY"


class AbstentionDecision(BaseModel):
    """Decision object generated by AbstentionPolicy."""
    status: OperationalPredictionStatus
    should_abstain: bool
    confidence_score: float = Field(..., ge=0.0, le=1.0)
    retained_coverage_tier: float = Field(..., ge=0.0, le=1.0)
    reason: Optional[AbstentionReason] = None
    explanation: str
    provenance: Dict[str, Any] = Field(default_factory=dict)


class AbstentionPolicy:
    """Evaluates whether an inference state is operationally supported."""

    def __init__(
        self,
        ood_threshold_abstain: float = 0.85,
        ood_threshold_diagnostic: float = 0.65,
        epistemic_uncertainty_threshold: float = 0.40,
    ):
        self.ood_threshold_abstain = ood_threshold_abstain
        self.ood_threshold_diagnostic = ood_threshold_diagnostic
        self.epistemic_uncertainty_threshold = epistemic_uncertainty_threshold

    def evaluate(
        self,
        hazard: str,
        ood_score: float,
        epistemic_uncertainty: float = 0.0,
        reference_available: bool = True,
        physical_valid: bool = True,
        severity_supported: bool = True,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> AbstentionDecision:
        """Evaluate inference state against operational support boundaries."""
        meta = metadata or {}
        confidence = float(max(0.0, min(1.0, 1.0 - ood_score * 0.7 - epistemic_uncertainty * 0.3)))

        # 1. Check independent truth reference availability
        if not reference_available:
            return AbstentionDecision(
                status=OperationalPredictionStatus.ABSTAIN,
                should_abstain=True,
                confidence_score=0.0,
                retained_coverage_tier=0.0,
                reason=AbstentionReason.REFERENCE_UNAVAILABLE,
                explanation=f"Independent ground truth reference is unavailable for {hazard}. Operational validation cannot be verified.",
                provenance={"hazard": hazard, "reference_available": False, **meta},
            )

        # 2. Check physical validity
        if not physical_valid:
            return AbstentionDecision(
                status=OperationalPredictionStatus.ABSTAIN,
                should_abstain=True,
                confidence_score=0.0,
                retained_coverage_tier=0.0,
                reason=AbstentionReason.PHYSICAL_INCONSISTENCY,
                explanation=f"Atmospheric state exhibits physical inconsistency violating conservation laws for {hazard}.",
                provenance={"hazard": hazard, "physical_valid": False, **meta},
            )

        # 3. Check severity limits
        if not severity_supported:
            return AbstentionDecision(
                status=OperationalPredictionStatus.ABSTAIN,
                should_abstain=True,
                confidence_score=round(confidence, 4),
                retained_coverage_tier=0.80,
                reason=AbstentionReason.SEVERITY_LIMIT_UNSUPPORTED,
                explanation=f"Hazard severity level exceeds certified operational boundaries for {hazard}.",
                provenance={"hazard": hazard, "severity_supported": False, **meta},
            )

        # 4. Check OOD bounds
        if ood_score >= self.ood_threshold_abstain:
            return AbstentionDecision(
                status=OperationalPredictionStatus.ABSTAIN,
                should_abstain=True,
                confidence_score=round(confidence, 4),
                retained_coverage_tier=0.80,
                reason=AbstentionReason.OOD_EXCEEDED,
                explanation=f"OOD score {ood_score:.3f} exceeds operational cutoff ({self.ood_threshold_abstain:.2f}) for {hazard}.",
                provenance={"hazard": hazard, "ood_score": ood_score, **meta},
            )

        # 5. Check epistemic uncertainty
        if epistemic_uncertainty >= self.epistemic_uncertainty_threshold:
            return AbstentionDecision(
                status=OperationalPredictionStatus.ABSTAIN,
                should_abstain=True,
                confidence_score=round(confidence, 4),
                retained_coverage_tier=0.85,
                reason=AbstentionReason.EPISTEMIC_UNCERTAINTY_HIGH,
                explanation=f"Epistemic ensemble uncertainty {epistemic_uncertainty:.3f} exceeds threshold ({self.epistemic_uncertainty_threshold:.2f}).",
                provenance={"hazard": hazard, "epistemic_uncertainty": epistemic_uncertainty, **meta},
            )

        # 6. Diagnostic tier
        if ood_score >= self.ood_threshold_diagnostic:
            return AbstentionDecision(
                status=OperationalPredictionStatus.DIAGNOSTIC_ONLY,
                should_abstain=False,
                confidence_score=round(confidence, 4),
                retained_coverage_tier=0.90,
                reason=None,
                explanation=f"State is in moderate OOD regime ({ood_score:.3f}); promoted for advisory diagnostics only.",
                provenance={"hazard": hazard, "ood_score": ood_score, **meta},
            )

        # 7. Fully supported
        return AbstentionDecision(
            status=OperationalPredictionStatus.PREDICT,
            should_abstain=False,
            confidence_score=round(confidence, 4),
            retained_coverage_tier=1.00,
            reason=None,
            explanation=f"Inference state is within certified in-distribution operational bounds for {hazard}.",
            provenance={"hazard": hazard, "ood_score": ood_score, **meta},
        )
